global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 您的 API 應用
  - job_name: 'api-app'
    static_configs:
      - targets: ['dev-api.giant-hpb.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    tls_config:
      insecure_skip_verify: true
    # 如果需要認證
    # basic_auth:
    #   username: 'your_username'
    #   password: 'your_password'